### ISSUE TITLE
物品输出物品会被吞

### ISSUE THREAD

**Issue by xfpuls** [EpimorphicPioneers/Gregic-Energistics#12]
io error while handling a recipe gtceu:smelting/smelt_raw_tungstate_ore_to_ingot outputs. holder: com.gregtechceu.gtceu.api.machine.multiblock.CoilWorkableElectricMultiblockMachine@3a557ec2
这是服务端后台报错

**Comment by YiRanMushroom** [comment]
我也遇到了这个问题，想问是不是这个IO不能发送回非其本身发配的任务的输出？

**Comment by xfpuls** [comment]
我发现这个好像是gtm的问题，我之前以为是ge的问题把总成换成总线还是会这样输出错误

**Comment by YiRanMushroom** [comment]
不对，总线和这个crafting io buffer的网络交互原理不同。我昨天试着pull了一下最新的branch，已经没有问题了。等merge吧。

**Comment by qwer523** [comment]
> 我也遇到了这个问题，想问是不是这个IO不能发送回非其本身发配的任务的输出？

是的，之前有回流隔离，因为作用不大并且增加不少代码负担，已经删除了

**Comment by qwer523** [comment]
> 我发现这个好像是gtm的问题，我之前以为是ge的问题把总成换成总线还是会这样输出错误

那我先关闭这个issue

**Comment by YiRanMushroom** [comment]
> > 我也遇到了这个问题，想问是不是这个IO不能发送回非其本身发配的任务的输出？
> 
> 是的，之前有回流隔离，因为作用不大并且增加不少代码负担，已经删除了

为什么到现在各个branch还不能merge到master？这几个branch东西我看了一下也测试了，Stocking Input Hatch/Bus还有一点小问题，其他基本都正常了。

**Comment by DancingSnow0517** [comment]
> > > 我也遇到了这个问题，想问是不是这个IO不能发送回非其本身发配的任务的输出？
> > 
> > 
> > 是的，之前有回流隔离，因为作用不大并且增加不少代码负担，已经删除了
> 
> 为什么到现在各个branch还不能merge到master？这几个branch东西我看了一下也测试了，Stocking Input Hatch/Bus还有一点小问题，其他基本都正常了。

现在还有功能没有实现
