### ISSUE TITLE
Crafting IO Buffer有时不能正确启动配方

### ISSUE THREAD

**Issue by YiRanMushroom** [EpimorphicPioneers/Gregic-Energistics#14]
如标题所说，Crafting IO Buffer有时不能正确启动配方，找不到具体的规律，但是其中一个例子是Extruder配方，似乎共享的物品和流体可能会造成问题，麻烦的是这个问题有时候出现有时候不出现，之前尝试Indium Tin Barium Titanium Cuprate Dust有时也不能启动，不知道什么原因。

**Comment by qwer523** [comment]
好的，我尝试复现一下

**Comment by YiRanMushroom** [comment]
这个问题有成功复现吗？我这边就是extruder不能使用。

**Comment by qwer523** [comment]
复现了，会在下个版本修复

**Comment by qwer523** [comment]
#21 修复了
