### ISSUE TITLE
存储输入总线的拉取逻辑存在问题

### ISSUE THREAD

**Issue by FwFeiVan** [EpimorphicPioneers/Gregic-Energistics#15]
At Gregtech Leisure1.2.3.4, Mod version 1.0.5
根据大机器并行的表现，我认为无论网络中存有多少被拉取的物品，机器只能读取到1组物品。若机器设置的并行数量所消耗的原料大于一组，则机器不会运行。
此处以电解粉为例：
黄玉粉一次电解消耗6个，最大并行为10；
![2d3befc55967a55e54285f29f40724ce](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/d3662392-6c61-4097-b1c8-6d330184d6c9)
![b2aaa6b29bce25fa45f06797c93022e6](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/37993428-d7c2-47fd-9b5a-65a2815d6055)

蓝宝石粉一次电解消耗5个，最大并行为12；
![2df1ba2e60d0fcb23ca624d9ebe17c5f](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/04acc17b-ddb5-402d-aea0-0f0b94b92081)
![18585383f65b2cc365c2d738dc9ff83b](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/59a9f6b4-0297-4c60-b139-1669685ae81f)

蓝黄玉粉一次消耗13个，最大并行为4.
![edcecf5f590feda57294a1136a977bbf](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/61c214dc-9431-4039-922b-2bf4906f73b9)
![118df9c03397ee5fe5711d29fd04c1d8](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/159519096/6789fcae-ad03-42f7-bc3c-14ea61e27e9c)

上述3种情形，若把机器并行数增加1，则机器不会运行。化工网络还有更多实例，此处不一一展示。
而换用普通的仓室，机器并行数调满仍然可以运行。所以我认为这可能并不是GTM的问题。

**Comment by FwFeiVan** [comment]
输入仓似乎还没写好，输入总线写好了，不会吞东西，就是有上面这个问题

**Comment by qwer523** [comment]
> At Gregtech Leisure1.2.3.4, Mod version 1.0.5 根据大机器并行的表现，我认为无论网络中存有多少被拉取的物品，机器只能读取到1组物品。若机器设置的并行数量所消耗的原料大于一组，则机器不会运行。 此处以电解粉为例： 黄玉粉一次电解消耗6个，最大并行为10； ![2d3befc55967a55e54285f29f40724ce](https://private-user-images.githubusercontent.com/159519096/338860250-d3662392-6c61-4097-b1c8-6d330184d6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMjUwLWQzNjYyMzkyLTZjNjEtNDA5Ny1iMWM4LTZkMzMwMTg0ZDZjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2EwN2RmZDQyMTE5MjY2Mjk5MzQxOTQ5MTY2NGZlYjlhMjNlZWU0NTU5YWU4ZWY0MGMxNzM2OGZjMTcxNGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPkhltDlUCLr6-8gN2bZyb_q3UCz8Ov-9TMTtbzSZAM) ![b2aaa6b29bce25fa45f06797c93022e6](https://private-user-images.githubusercontent.com/159519096/338860263-37993428-d7c2-47fd-9b5a-65a2815d6055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMjYzLTM3OTkzNDI4LWQ3YzItNDdmZC05YjVhLTY1YTI4MTVkNjA1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mzg3MTA1NDQ5OWI0YTYyYzlmM2MwY2JlNjAxZTU5NWY3Y2MyNjRmYzNmNGNlNzAwYzkwNTRjNmNhM2M3YjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TJ1jcMxnigGkZr2ZX2raWSCVO-74LoPjDK6_jBcX7Ys)
> 
> 蓝宝石粉一次电解消耗5个，最大并行为12； ![2df1ba2e60d0fcb23ca624d9ebe17c5f](https://private-user-images.githubusercontent.com/159519096/338860282-04acc17b-ddb5-402d-aea0-0f0b94b92081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMjgyLTA0YWNjMTdiLWRkYjUtNDAyZC1hZWEwLTBmMGI5NGI5MjA4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTE5MTc2YWM2ZjhkM2MxZjdlOWExYjc2YjA1NmY5NGQ2NWFkNzRiZGNiYzMzMmYzMDBiNjg2ZGE3ZDBhZTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ZOyQ2znpxT_SOlpVTR98Nt5LQmKX4OF0xCIVaNLcoc) ![18585383f65b2cc365c2d738dc9ff83b](https://private-user-images.githubusercontent.com/159519096/338860293-59a9f6b4-0297-4c60-b139-1669685ae81f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMjkzLTU5YTlmNmI0LTAyOTctNGM2MC1iMTM5LTE2Njk2ODVhZTgxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGIzYWQ4OGRkZTM1MTAyMmRmODg1ZTU3ZTM1NmIzN2ZhOTQ1OGMwMDNhMGM5Zjk3YWFiNGY5ZmU1ZGRiZGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VBS4NJ9M4w0Na3FdkZY1OWEsw4YdkjTBw-Ib35QCI80)
> 
> 蓝黄玉粉一次消耗13个，最大并行为4. ![edcecf5f590feda57294a1136a977bbf](https://private-user-images.githubusercontent.com/159519096/338860312-61c214dc-9431-4039-922b-2bf4906f73b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMzEyLTYxYzIxNGRjLTk0MzEtNDAzOS05MjJiLTJiZjQ5MDZmNzNiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGU3MmNhMjM0ZGNjYzc2ZjM4ZDUzMzRiMmRjNjg4YWM0ZjExYWI1YTc5MDNmMmUwN2M1YWM0YzIyYTlmYjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h2uMIthzkwBPtRfCMiRKaahbxIVmYQ-VP4XigPflIcQ) ![118df9c03397ee5fe5711d29fd04c1d8](https://private-user-images.githubusercontent.com/159519096/338860328-6789fcae-ad03-42f7-bc3c-14ea61e27e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzQ3MjksIm5iZiI6MTcxODQzNDQyOSwicGF0aCI6Ii8xNTk1MTkwOTYvMzM4ODYwMzI4LTY3ODlmY2FlLWFkMDMtNDJmNy1iYzNjLTE0ZWE2MWUyN2U5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNjUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjEwZjBjM2E1NjI1NTQ5MzIyNTYwZTFhODAwZGRiY2RjMjNkNTJiMjkxZTRkNmNmYjJmNGY1YTg1ZTRmZGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VKkloypNZnTLTaduEZts5VSe_TVC5tSAxBRFiDB18x8)
> 
> 上述3种情形，若把机器并行数增加1，则机器不会运行。化工网络还有更多实例，此处不一一展示。 而换用普通的仓室，机器并行数调满仍然可以运行。所以我认为这可能并不是GTM的问题。

已经修复了

**Comment by qwer523** [comment]
> 这个东西bug还挺严重的，经常销毁流体不工作。

应该也修复了，我还得进一步测试一下

**Comment by qwer523** [comment]
#19 修复了
