### ISSUE TITLE
总成样板的液体会乱窜 另外在GTleisure 1.3中会崩溃

### ISSUE THREAD

**Issue by xfpuls** [EpimorphicPioneers/Gregic-Energistics#16]
[错误报告-2024-6-15_22.58.43.zip](https://github.com/user-attachments/files/15857512/-2024-6-15_22.58.43.zip)

**Comment by xfpuls** [comment]
补充一下总成样板乱窜 比如在一台机器当中有两个以上的样板总成 一旦超出机器处理剩下的流体会乱窜 或者说是另外的样板总成把原本需要合成的配方内的流体乱窜过来了

**Comment by qwer523** [comment]
#17
#6 
和以上issue为相同问题，会一并解决
