### ISSUE TITLE
You should've PR'd these to GT modern instead of making an addon

### ISSUE THREAD

**Issue by screret** [EpimorphicPioneers/Gregic-Energistics#23]
Would've been much better as they're all base mod features on 1.12 & 1.7.

**Comment by qwer523** [comment]
Yes, Arbor told me. I'm happy to do this job.

**Comment by Ghostipedia** [comment]
+1 I've spent tonight looking through the AE Busses and Hatches this mod has and they are awesome! If you're around in the GTCEU discord I have plenty of feedback for merging these into GTM cleanly :)

**Comment by qwer523** [comment]
I have joined, you can find me @gateguardian5233
