### ISSUE TITLE
Crash with GTCEU 1.3.0-a-build817 and GregicEnergistics

### ISSUE THREAD

**Issue by Ghostipedia** [EpimorphicPioneers/Gregic-Energistics#24]
After placing down a Crafting Input Slave on a multiblock, my game crashes.

I have provided a crash log below 

https://mclo.gs/EKVqnWS

**Comment by qwer523** [comment]
Crafting Input Slave is an incomplete work. In fact, Crafting IO Buffer has a series of technical issues that have delayed my progress in completing it, and I am happy to discuss them with you on discord.
