### ISSUE TITLE
样板IO镜像并不能复制原总成内的物品

### ISSUE THREAD

**Issue by FwFeiVan** [EpimorphicPioneers/Gregic-Energistics#25]
虽然最新build可以用闪存复制样板总成的信息，IO镜像点开确实可以看到和原总成相同的界面，并且样板修改也可以直接在镜像内操作
但是镜像最重要的功能是共享其内部的物品，让多台机器读取同一个总成的物品从而并行一个配方（没错就是纠缠方块）

因此IO镜像没有必要同步样板信息，只需要同步总成内的物品与总成的电路设置/不消耗物品设置即可。即让当前机器读取到对应总成之内的物品与流体，同时产物回流至原总成的网络。

**Comment by qwer523** [comment]
镜像还没做好，以上功能都会做
