### ISSUE TITLE
部分机器使用样板总成会导致存档频繁崩溃

### ISSUE THREAD

**Issue by FwFeiVan** [EpimorphicPioneers/Gregic-Energistics#27]
at Gregtech Leisure 1.3.0

目前我大量使用样板总成当me输出，在gtm自带机器以及kjs定义的部分机器上没有出现问题。
但是样板总成放在太空电梯资源模块以及集成矿石处理厂都会导致频繁崩溃。并不是炸档，而是一段时间之后崩溃，报告显示对应机器上的样板总成有问题。

（为什么都和矿有关

**Comment by qwer523** [comment]
请测试最新的构建
