### ISSUE TITLE
样板总成在一些特定的情况下会丢失样板

### ISSUE THREAD

**Issue by xfpuls** [EpimorphicPioneers/Gregic-Energistics#29]
在样板总成里看不到有样板 在样板管理也搜不到 也没有隐藏样板 但是在ae里还是能显示可以合成而且有概率会合成返回到ae 这好像是显示问题？

**Comment by xfpuls** [comment]
在有一个满三分之二的样板总成里只显示5 6个 把样板总成拆了那三分之二的样板会全部消失 要重新写样板

**Comment by qwer523** [comment]
样板总成已经合并进gtm
