### ISSUE TITLE
流体输入仅存在ME Stocking Input Hatch时不能按预期启动配方原材料检测。

### ISSUE THREAD

**Issue by YiRanMushroom** [EpimorphicPioneers/Gregic-Energistics#31]
如标题，仅存在Stocking Input Hatch时不能按预期启动配方原材料检测，可能的原因是在那时无法启动handleRecipeInner。

在这个issue中有提到。

https://github.com/liansishen/GTMThings/issues/11

**Comment by qwer523** [comment]
会在合并进gtm时重写

**Comment by qwer523** [comment]
已弃用，请使用gtm提供的ME Stocking Input Hatch/Bus
