### ISSUE TITLE
输入总成物品丢失

### ISSUE THREAD

**Issue by foxwhite25** [EpimorphicPioneers/Gregic-Energistics#32]
https://github.com/user-attachments/assets/7a635481-a3e7-4c31-885c-eb76982acbae

不知道为什么有时候会丢失物品输入，有时候也会连流体一起丢失了

**Comment by qwer523** [comment]
输入总成使用的是原版的配方处理逻辑，不太可能出现这种情况，你确定是使用的github action里的版本吗

**Comment by foxwhite25** [comment]
我发现原来GT leisure作者维护了自己的一个fork，貌似他自己的代码出现的问题，和upstream无关
