### ISSUE TITLE
[BUG] ME 存储输入仓无法显示流体工具提示

### ISSUE THREAD

**Issue by UraraChiya** [EpimorphicPioneers/Gregic-Energistics#35]
在 ME 存储输入仓的标记位置标记流体后，无法通过光标悬停在上面查看标记的是何种流体。
![image](https://github.com/user-attachments/assets/646c991c-71be-4bee-8c8b-af692ed5f000)

**Comment by qwer523** [comment]
已弃用，请使用gtm提供的ME Stocking Input Hatch/Bus
