### ISSUE TITLE
[BUG] ME 存储输入总线破坏后不会掉落共享库存内储存的物品。

### ISSUE THREAD

**Issue by UraraChiya** [EpimorphicPioneers/Gregic-Energistics#36]
按 Shift 放入物品后无法取出，破坏后物品无掉落。
![image](https://github.com/user-attachments/assets/857c25f9-0d18-478d-8fec-035aa14f2852)
通过按 Shift 放入
![image](https://github.com/user-attachments/assets/4535fe33-abfd-43c8-892d-c04a3fd3c6c6)
破坏后
![image](https://github.com/user-attachments/assets/3d8f7f9f-f0c9-4363-be82-e9ec893adcc9)
![image](https://github.com/user-attachments/assets/49ec8d37-dddf-46ac-b0bb-7aa3b0df48eb)

**Comment by LinYingLY** [comment]
存在左下角的箱子图标里面了

**Comment by UraraChiya** [comment]
> 存在左下角的箱子图标里面了

呀，的确如此。

**Comment by qwer523** [comment]
已弃用，请使用gtm提供的ME Stocking Input Hatch/Bus
