### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by LinYingLY** [EpimorphicPioneers/Gregic-Energistics#5]
版本1.0.5
ME样板IO总成内含有样板时破坏其方块不会掉落内部物品
一个多方块机器在同时使用输入总成和ME样板IO总成时（将ME样板IO总成视为输出端），会直接吞掉产物 没有输出
还有就是直接从无线样板访问终端中放入样板（不清楚实体面板的是不是） 网络中无法立即显示配方 需要我自己过去将样板拿起来再放进去才显示

希望能支持extendedae 的扩展样板管理终端
还有可以出类似镜像的 或者说高版本那种内存卡复制样板供应器的配置（包括样板）的东西 会很方便

**Comment by LinYingLY** [comment]
补充一下 在extendedae中的扩展样板管理器中只能看到样板总成的名字 没有物品栏 而且只要网络中存在样板总成就无法正常操作样板管理终端的界面

**Comment by ZHENGLOC** [comment]
吞东西问题确实很严重，玩起来太糟心了

**Comment by YiRanMushroom** [comment]
GregTech原版的输入输出总线和仓本来就bug极其多，吞物品十分常见。这个估计难写，我也试了很久修也搞不好。不知道这个作者是怎么写的。

**Comment by ZHENGLOC** [comment]
> GregTech原版的输入输出总线和仓本来就bug极其多，吞物品十分常见。这个估计难写，我也试了很久修也搞不好。不知道这个作者是怎么写的。

我还以为只有我玩的时候被吞物品，原来都有，气笑了，有时候搓东西ae里忽然停了真给我整红温了

**Comment by LinYingLY** [comment]
1more 建议给总成加一个阻挡模式 然后今天合金冶炼炉总是会出现明明材料齐全且刚能烧的配方下一秒就烧不动了

**Comment by YiRanMushroom** [comment]
> > GregTech原版的输入输出总线和仓本来就bug极其多，吞物品十分常见。这个估计难写，我也试了很久修也搞不好。不知道这个作者是怎么写的。
> 
> 我还以为只有我玩的时候被吞物品，原来都有，气笑了，有时候搓东西ae里忽然停了真给我整红温了

我反正用的时候发现Input bus/hatch有可能销毁输入工作不正常。output bus经常销毁输出，output hatch根本不检测。

**Comment by qwer523** [comment]
不掉样板的问题已经修复了；
我已经移除了作用不大的回流隔离功能，应该不会再有吞产物的情况了；
关于样板管理终端的问题DancingSnow在修；

**Comment by qwer523** [comment]
> 1more 建议给样板总成加一个阻挡模式 然后今天合金冶炼炉总是会出现明明材料齐全且刚能烧的配方下一秒就烧不动了

能详细描述一下吗，我尝试复现一下

**Comment by YiRanMushroom** [comment]
> 镜像和库存总线正在写，以上修复会在下个版本里

库存总线是GTNH的那个吗？

还有问一下大佬大概研究了GTM和AE2多久才写出这些的，我写GTM相关还好，AE的是完全看不懂。

在问一下这个Item Output Buffer是做到了不定长度的了吗？我看原版的是一个16长度的Array，超过哪个就销毁了

**Comment by qwer523** [comment]
是的，gtm的库存总线本质是一个ME接口，并不能直接从网络提取原料，所以我计划加一个新的；
研究了一下，其实我也不太懂；
我用Map存的；

**Comment by LinYingLY** [comment]
> > 1more 建议给样板总成加一个阻挡模式 然后今天合金冶炼炉总是会出现明明材料齐全且刚能烧的配方下一秒就烧不动了
> 
> 能详细描述一下吗，我尝试复现一下

比如说我下单10个高速钢-g线圈(高速钢-g:14号配方 碳化钨:12号配方)+10个散热片(碳化钽:12号配方)，最后的结果是12号总成中剩余1个钽粉 3个钨粉 4个碳粉和1500mb气态氦(完全足够做3份碳化钨和1份碳化钽并且多出600mb气态氦)、14号总成中剩余一份高速钢-g的材料但是没有剩余气态氦
![09cdd9b4-a33c-47d8-8fff-934d0c9a8af6](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/62381515/6f8346b2-a1ad-4d28-97a1-74e6c35c6b59)
四联合金冶炼炉配置如图，轴对称的样板总成是同电路且样板完全相同 不排除是AE那边发配出问题了 但是加一个阻挡模式可能可以解决

**Comment by qwer523** [comment]
好的，感谢

**Comment by LinYingLY** [comment]
补充 经测试在样板管理终端中给样板总成放入样板无效，必须手动再过去重新放样板

**Comment by LinYingLY** [comment]
![924a55a4-6887-41a6-b7c1-c17503348c20](https://github.com/EpimorphicPioneers/Gregic-Energistics/assets/62381515/806e6178-761d-41c5-82ca-1782ec012f79)
补充 使用样板总成的大型激光蚀刻机无法运行配方

**Comment by DancingSnow0517** [comment]
> 补充一下 在extendedae中的扩展样板管理器中只能看到样板总成的名字 没有物品栏 而且只要网络中存在样板总成就无法正常操作样板管理终端的界面

这点在更新 extendedae 后解决，鱼大做了特殊的gtm兼容
