### ISSUE TITLE
Input Buffer不可以Distinct流体

### ISSUE THREAD

**Issue by YiRanMushroom** [EpimorphicPioneers/Gregic-Energistics#6]
Input Buffer就算是打开了distinct bus也不可以distinct流体。

我只是提出这个问题让您知道，这个问题我记得很难解决，必须要重写流体的检测（什么FluidCapatibility::limitParallel什么的，我也记不清了）。

想知道ME Crafting IO Buffer会不会之后也出现这个问题（我问这个是因为我测试不了，产物老是被销毁），这个有没有可能解决。（我估计也不好搞）

**Comment by qwer523** [comment]
感谢反馈，我会尝试解决这个问题；
IO总成会有，目前只实现了样板之间的隔离，仓室之间的隔离会和上面同步修复；

**Comment by YiRanMushroom** [comment]
我估计十分困难，你如果想解决估计得写一个新的IRecipeHandlerTrait，可以同时处理两种，分别是FluidIngredient和Ingredient我认为也没有很大必要有这个功能，现在没有这个唯二头疼的就是Fluid Solidifier的问题和一些Cable需要不同橡胶的问题了。

**Comment by YiRanMushroom** [comment]
难的不是怎么distinct流体，难的是怎么给在同一个buffer中的物品流体分到同一个“组”，怎么同时Handle这两种Ingredient。

**Comment by qwer523** [comment]
gtm的dev说会解决这个问题
